### ISSUE TITLE
Missing node in cluster leads to timeout for proxy client

### ISSUE THREAD

**Issue by carlduevel** [datastax/zdm-proxy#90]
Switching an application to use the proxy instead of  using C* directly timeouts occur on and off on the application side:

`[com.datastax.oss.driver.api.core.DriverTimeoutException: [s0|control|id: 0x795f84e4, L:/172.18.0.3:48592 - R:cassandra_proxy/172.18.0.2:9042] Protocol initialization request, step 1 (OPTIONS): timed out after 5000 ms]`

Matching lines in the proxy log:

`Client Handler could not be created: ORIGIN-CONNECTOR context timed out or cancelled while opening connection to ORIGIN: context deadline exceeded`

Though the error message does not contain an IP address I presume this is caused by a faulty entry in the C* table that pointed to a non-existing node, because the IP of that node is coming up in the proxy log before the error. 

My question is: As the application with the DataStax Java Driver did not have a problem connecting to the cluster with the missing node - why is the proxy?

The proxy ran as a side car container for each application container. So, there was one proxy used by each client instance.

┆Issue is synchronized with this [Jira Task](https://datastax.jira.com/browse/ZDM-510) by [Unito](https://www.unito.io)
┆Components: Proxy
┆Issue Number: ZDM-510

**Comment by carlduevel** [comment]
[Here is a reproduction of this issue with docker](https://github.com/carlduevel/zdm-proxy-timeout-reproduction).

**Comment by joao-r-reis** [comment]
We recommend users in our docs to use multiple instances of ZDM proxy so you can create a "zdm" cluster and have that cluster be shared between all your applications. This was the model that we had in mind when designing the proxy so that if one C* node is failing only 1 zdm proxy will be affected by it and the others will remain healthy. 

We can definitely improve zdm so that it avoids connecting to unhealthy nodes completely but for now we recommend users to use at least 3 zdm proxy instances and to avoid shutting down C* nodes while the migration is in place.

**Comment by carlduevel** [comment]
Hi @joao-r-reis,

thanks for your input!
I thought about that and tried it [on this branch](https://github.com/carlduevel/zdm-proxy-timeout-reproduction/blob/multiple_proxies/docker-compose.yml) with the same result. 

In this example all three proxies are configured to talk to all three nodes, so each of them roughly fails
on every third request. This leads to the same exceptions for the client.

**Comment by joao-r-reis** [comment]
You need to configure `ZDM_PROXY_TOPOLOGY_ADDRESSES` and `ZDM_PROXY_TOPOLOGY_INDEX` ([these 2)](https://github.com/datastax/zdm-proxy/blob/main/proxy/pkg/config/config.go#L27-L28).

The addresses env var must be a comma separated list of the proxy IPs (it must be in the same order in all proxies) and the proxy index must be the index of that proxy in the addresses list. For example, let's say you have 3 proxies with addresses `127.0.0.1`, `127.0.0.2` and `127.0.0.3`, in the `127.0.0.1` proxy you would configure it like this:

```
ZDM_PROXY_TOPOLOGY_ADDRESSES=127.0.0.1,127.0.0.2,127.0.0.3
ZDM_PROXY_TOPOLOGY_INDEX=0
```

The `127.0.0.1` proxy would be configured like this:

```
ZDM_PROXY_TOPOLOGY_ADDRESSES=127.0.0.1,127.0.0.2,127.0.0.3
ZDM_PROXY_TOPOLOGY_INDEX=1
```

If you don't configure these settings the proxy will present itself as a single proxy cluster. You should be able to verify that this configuration is correct by looking at the first lines in the proxy logs (the entire config is printed except password).

It might be hard to do this with docker compose because I believe you can't provide hostnames to `ZDM_PROXY_TOPOLOGY_ADDRESSES` but I could be wrong.

**Comment by joao-r-reis** [comment]
Also, our documentation focuses mostly on running the proxy with https://github.com/datastax/zdm-proxy-automation so we don't really document these 2 settings anywhere from what I can see, I'll create an issue for this.

**Comment by carlduevel** [comment]
Thanks @joao-r-reis! could reproduce the behavior with the topology parameters just like you described them: https://github.com/carlduevel/zdm-proxy-timeout-reproduction/tree/multiple_proxies_with_topology
